#define theme (stat(984))

		itemDef
		{
			style			WINDOW_STYLE_SHADER
			rect			FULLSCREEN_WIDE
			background		"sr_menu_bg_1"
			visible			when(theme == 0)
			decoration
		}

		itemDef
		{
			style			WINDOW_STYLE_SHADER
			rect			FULLSCREEN_WIDE
			background		"sr_menu_bg_2"
			visible			when(theme == 1)
			decoration
		}

		itemDef
		{
			style			WINDOW_STYLE_SHADER
			rect			FULLSCREEN_WIDE
			background		"sr_menu_bg_3"
			visible			when(theme == 2)
			decoration
		}

		itemDef
		{
			style			WINDOW_STYLE_SHADER
			rect			FULLSCREEN_WIDE
			background		"sr_menu_bg_4"
			visible			when(theme == 3)
			decoration
		}

		itemDef
		{
			style			WINDOW_STYLE_SHADER
			rect			FULLSCREEN_WIDE
			background		"sr_menu_bg_5"
			visible			when(theme == 4)
			decoration
		}

		itemDef
		{
			style			WINDOW_STYLE_SHADER
			rect			FULLSCREEN_WIDE
			background		"sr_menu_bg_6"
			visible			when(theme == 5)
			decoration
		}

		itemDef
		{
			style			WINDOW_STYLE_SHADER
			rect			FULLSCREEN_WIDE
			background		"sr_menu_bg_7"
			visible			when(theme == 6)
			decoration
		}
